[workspace]
channels = ["conda-forge"]
name = "Parte1"
platforms = ["win-64","linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
mypy = ">=1.15.0,<2"
numpy = ">=2.2.6,<3"
pytest = ">=8.3.5,<9"

[pypi-dependencies]
yogi = { git = "https://github.com/jutge-org/yogi" }